# Data Structures

## ToolBase
+ title: `AdonisJS` (required, string) - Titulo da ferramenta.
+ link: `https://adonisjs.com/` (optional, string) - URL da ferramenta.
+ description: `foo bar description` (optional, string) - Descrição da ferramenta.
+ tags: `nodejs`, `react`, `react native` (required, array[string]) - Tags relacionadas.

## ToolResponse
+ id: `5d0abbce762b5779d92bdbb0` (required, string) - ID da ferramenta.
+ Include (ToolBase)

## ToolError400
+ code: `bad_request` (required, string) - Código de erro
+ error: `O campo nome não pode ser vazio` (required, string) - Mensagem de erro

## ToolError401
+ code: `unauthorized` (required, string) - Código de erro
+ error: `Token inválido` (required, string) - Mensagem de erro

## ToolError404
+ code: `not_found` (required, string) - Código de erro
+ error: `Ferramenta não encontrada` (required, string) - Mensagem de erro
