language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

services:
  - mongodb

install:
  - yarn

before_script:
  - sleep 15

script:
  - commitlint-travis
  - yarn test:coverage

before_deploy:
  - yarn build:docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master



