# Data Structures

## UserProfileBase
+ name: `Foo Bar` (required, string) - Nome do usuário.
+ email: `foo@bar.com` (required, string) - E-mail do usuário.

## UserResponse
+ _id: `5d0abbce762b5779d92bdbb0` (required, string) - ID do usuário.
+ Include (UserProfileBase)

## UserError400
+ code: `bad_request` (required, string) - Código de erro
+ error: `Oops! Erro ao tentar processar a requisição.` (required, string) - Mensagem de erro
+ details: `Insira um e-mail válido` (optional, array[string]) - Detalhe da mensagem
