## Perfil [/me]

### Informações [GET]

+ Request Pegando informações (application/json)

    + Headers

                Authorization: Bearer <token>

+ Response 200
    + Attributes (UserResponse)


### Alterando [PUT]

+ Request Alterando (application/json)
    + Attributes (UserBase)

    + Headers

                Authorization: Bearer <token>

+ Response 200
    + Attributes (UserBase)


+ Request E-mail inválido (application/json)
    + Attributes (UserBase)
      + email: `email` (required, string)

    + Headers

                Authorization: Bearer <token>

+ Response 400 (application/json)
    + Attributes (UserError400)
